Makefile
clusterctl-settings.json

How to verify:
```
cat <<EOF >  ~/.cluster-api/clusterctl.yaml
providers:
- name: "elf"
url: "https://github.com/smartxworks/cluster-api-provider-elf/releases/latest/infrastructure-components.yaml"
type: "InfrastructureProvider"
EOF
clusterctl init -i elf
```

Add default docker repo to fix `clusterctl init -i elf`

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
go.mod
go.sum
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go
pkg/session/tower.go
pkg/util/tower.go
test/e2e/vm_helpers.go
test/fake/tower.go

[升级 Tower SDK 2.0](https://github.com/smartxworks/cluster-api-provider-elf/issues/21)
创建和删除集群通过（已调用所有 Tower SDK 依赖的接口）
目前兼容 Tower 1.9

Upgrade Tower SDK to v2.0

---

api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachinetemplates.yaml
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/vm.go
pkg/util/machines.go
pkg/util/machines_test.go
templates/cluster-template.yaml
test/e2e/data/infrastructure-elf/cluster-template-conformance.yaml
test/e2e/data/infrastructure-elf/cluster-template-cp-ha.yaml
test/e2e/data/infrastructure-elf/cluster-template-kcp-remediation.yaml
test/e2e/data/infrastructure-elf/cluster-template-kcp-scale-in.yaml
test/e2e/data/infrastructure-elf/cluster-template-md-remediation.yaml
test/e2e/data/infrastructure-elf/cluster-template-node-drain.yaml
test/e2e/data/infrastructure-elf/cluster-template.yaml
test/e2e/data/infrastructure-elf/kustomization/base/cluster-template.yaml

增加不配置网卡的支持
通过移除 network index，增加 NetworkTypeNone 类型，默认不作网卡的配置。
1. 移除 network index
2. fix 删除创建中集群无法删除（创建中的 ElfMachine 无法被删除导致的原因）
测试 yaml
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
labels:
cluster.x-k8s.io/cluster-name: elfk8s158
name: elfk8s158
namespace: default
spec:
clusterNetwork:
pods:
cidrBlocks:
- 100.96.0.0/11
controlPlaneRef:
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
name: elfk8s158-control-plane
infrastructureRef:
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfCluster
name: elfk8s158
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfCluster
metadata:
name: elfk8s158
namespace: default
spec:
cluster: 576ad467-d09e-4235-9dec-b615814ddc7e
controlPlaneEndpoint:
host: 192.168.30.158
port: 6443 …
```

Add NetworkType NONE and remove NetworkIndex

---

controllers/elfmachine_controller_test.go
pkg/service/errors.go
pkg/service/vm.go

https://github.com/smartxworks/cluster-api-provider-elf/issues/26
通过增加支持 Tower VM ID 对虚拟机进行操作。
测试 yaml
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
labels:
cluster.x-k8s.io/cluster-name: elfk8s158
name: elfk8s158
namespace: default
spec:
clusterNetwork:
pods:
cidrBlocks:
- 100.96.0.0/11
controlPlaneRef:
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
name: elfk8s158-control-plane
infrastructureRef:
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfCluster
name: elfk8s158
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElfCluster
metadata:
name: elfk8s158
namespace: default
spec:
cluster: 576ad467-d09e-4235-9dec-b615814ddc7e
controlPlaneEndpoint:
host: 192.168.30.158
port: 6443
tower:
authMode: LOCAL
password: …
```

Fix VM operation use tower VM ID

---

api/v1beta1/conditions_consts.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/errors.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go
test/e2e/ha_test.go
test/e2e/vm_helpers.go

https://github.com/smartxworks/cluster-api-provider-elf/issues/30
通过 Tower 接口正常关闭虚拟机如果遇到 JOB_VM_SHUTDOWN_TIMEOUT 错误，就使用强制关机。
- 重新命名 shut down：正常关机；power off 强制关机
1. 单测请看代码部分
2. 手动测试
2.1 创建集群
2.2 关闭 worker 节点的 ACPI
```bash
vi /etc/default/grub
GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet noacpi acpi=off"
grub2-mkconfig -o /boot/grub2/grub.cfg
systemctl reboot
```
第一次无法正常关机失败
第二次使用强制关机成功

Fix the virtual machine cannot be deleted due to ACPI exception

---

api/v1beta1/elfcluster_types.go
api/v1beta1/elfmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachines.yaml

```bash
kubectl get elfcluster
NAME      READY   TOWER
elfk8s3   true    tower.caas.smtx.io
```
```bash
kubectl get elfmachines
NAME                         READY    PROVIDERID                                   IP           MACHINE
elfk8s3-worker-zbmnm         true     elf://1aae6679-98c3-4a5c-a5b9-a976c8ef9ba6   10.255.1.8   elfk8s3-md-0-76c75b7cd5-wcspt
elfk8s3-control-plane-7n9wz  true     elf://af567d8a-a9ac-4741-b7d9-73ef369e8a64   10.255.1.7   elfk8s3-control-plane-t5plq
```

Update ElfCluster and ElfMachine printcolumns

---

api/v1beta1/conditions_consts.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go

创建新的 ElfMachine ，device先不设置 IP，之后再设置 IP。

Wait for ip allocation when vm ipv4 network device without ip

---

api/v1beta1/conditions_consts.go
controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
controllers/elfmachine_controller_test.go

1. 没有设置 ControlPlaneEndpoint 不再直接抛异常，而是等待
2. 增加 ControlPlaneEndpointReadyCondition，提高可观测性

Refactor reconciling control plane endpoint

---

api/v1beta1/elfcluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfclusters.yaml
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
templates/cluster-template.yaml

Add option ElfCluster.VMGracefulShutdown to support shutting down VMs gracefully or forcefully.

Add cluster machine graceful shutdown option

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go

修复ElfCluster/ElfMachine 在tower失联场景下，强制删除失败问题
1.  失联场景下，tower session过期，需要重新获取tower session失败，会跳过reconcileDelete
2.  失联场景下，cape重启，需要重新获取tower session，重新获取tower session失败，会跳过reconcileDelete
Test
测试集群
创建完成后修改tower地址保证tower连接不上
cape 报错连接不上tower
正常删除cape一直报错无法删除
添加强制删除annotations
强制删除成功
vm删除被跳过

Fix force delete failed when tower is disconnected

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/errors.go

1. 当创建虚拟机遇到 cloud-init 错误，设置 failure
2. 优化 task 的处理逻辑，把删除虚拟机和创建虚拟机相关的 task 代码合并
```yaml
status:
conditions:
- lastTransitionTime: "2022-11-01T08:25:20Z"
message: "Cannot unwrap Ok value of Result.Err.\r\ncode: CREATE_VM_FORM_TEMPLATE_FAILED\r\nmessage:
{\"data\":{},\"ec\":\"VM_CLOUD_INIT_CONFIG_ERROR\",\"error\":{\"msg\":\"[VM_CLOUD_INIT_CONFIG_ERROR]The
gateway [192.168.31.215] is unreachable. \"}}"
reason: TaskFailure
severity: Info
status: "False"
type: Ready
- lastTransitionTime: "2022-11-01T08:24:58Z"
status: "True"
type: TowerAvailable
- lastTransitionTime: "2022-11-01T08:25:20Z"
message: "Cannot unwrap Ok value of Result.Err.\r\ncode: CREATE_VM_FORM_TEMPLATE_FAILED\r\nmessage:
{\"data\":{},\"ec\":\"VM_CLOUD_INIT_CONFIG_ERROR\",\"error\":{\"msg\":\"[VM_CLOUD_INIT_CONFIG_ERROR]The …
```

Set cluster failure when cloning VM with cloud-init config error

---

api/v1beta1/elfmachine_types.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/label/label.go
pkg/service/errors.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go
test/fake/tower.go

Changes:
1.  支持在elfMachine删除时，等待ELF CSI 挂载的volume全部卸载完成后，在删除对应的VM
Tests:
1.  vm挂载ELF CSI 创建的volume，删除elfMachine
ks集群
ELF CSI volume挂载的VM
直接删除elfMachine
cape日志
删除machine等待volume全部被卸载
vm对应ELF CSI挂载的volume全部卸载完成，并开始关机
machine 成功删除
2.  vm挂载ELF CSI 创建的volume，删除ks集群
ks集群
ELF CSI volume挂载的VM
跳过volume detach等待，直接关机删除vm

SKS-489: Wait for VM Volumes created by ELF CSI to be detached when ElfMachine is being deleted

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/errors.go
pkg/util/tower.go

测试
1.创建集群
2.关闭 CAPE 服务
3.关闭其中一个虚拟机，并移到回收站
4.启动 CAPE 服务，未发现在回收站的虚拟机被开机
5.删除集群或删除在回收站虚拟机对应的 Machine，在回收站的虚拟机没有被删除

Set ElfMachine to failure status when the VM was moved to the Tower recycle bin

---

templates/cluster-template.yaml

集群名：1234567
命名空间：999999
KCP：111111
MD：222222
**字符串命名场景正常**

Update cluster template for ytt support numeric string vars

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go

SKS-151：删除所有的集群后 managed 标签没有被删除。
集群共用标签放在最后删除，可以进一步提高标签被删除的概率。

Remove the 'cape-managed' label for VM when there is no clusters

---

api/v1beta1/elfmachine_types.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/errors.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go
test/fake/tower.go

问题：
[SKS-645] VM异常场景下，capi machine配置nodeDrainTimeout， 替换节点失败 - Jira http://jira.smartx.com/browse/SKS-645
问题根因：
STS Pod在k8s node status not ready的场景下，无法正常删除，无法触发ELF CSI volume detach，进而影响ELF Machine的删除
修复方案：
[[SKS-645]K8s节点失联处理的设计文档](https://docs.google.com/document/d/19-GjuJT29Q8GwxpLw2aS7lEVPyQYohrArjROzHlz2kw/edit#)
测试：
测试步骤:
1. 创建一个安装ELF CSI，logging,monitoring开启的sks集群
2. 删除worker node hw-sks-test-1.23-elf-op-3-workergroup-mp6hj 的网卡
3. K8s node hw-sks-test-1.23-elf-op-3-workergroup-mp6hj显示not ready
4. delete Machine hw-sks-test-1.23-elf-op-3-workergroup-d475b4648-clmld
```
I1122 12:34:43.659300       1 machine_controller.go:318] "Draining node" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/hw-sks-test-1.23-elf-op-3-workergroup-d475b464 …
```

SKS-645: Remove 'shouldWaitForVMVolumesToBeDetached' when ElfMachine is deleted

---

controllers/elfmachine_controller.go
pkg/util/tower.go

SKS-678
当前 vm task 相关的日志输出信息较少，需要到 Tower 查看更多的信息。
需要针对 task 不同的状态，输出不同相关的字段信息。
任务进行中，增加 taskDescription
```yaml
"msg"="Waiting for VM task done" "elfCluster"="elfk8s1" "elfMachine"="elfk8s1-control-plane-w2t2x" "namespace"="default" "taskDescription"="Power off VM elfk8s1-control-plane-w2t2x" "taskRef"="claqh27ck4ys81tud504w4vkc" "taskStatus"="PENDING" "vmRef"="79a9e899-2524-497a-9c00-67e272558d1b"
```
任务失败，增加 taskErrorCode、taskDescription
```yaml
"error"="VM task failed" "elfCluster"="elfk8s1" "elfMachine"="elfk8s1-control-plane-gzbsg" "namespace"="default" "taskDescription"="Create a VM elfk8s1-control-plane-gzbsg from a VM template Rocky-k8s-1.22.13-0831-2" "taskErrorCode"="CREATE_VM_FORM_TEMPLATE_FAILED" "taskErrorMessage"="Cannot unwrap Ok value of Result.Err.\r\ncode: …
```

Add more task details for vm task logs

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/errors/consts.go

增加 3 个 elfMachine failed 的错误码，用于填入 `elfMachine.status.failureReason` ：
* `CloudInitConfigError`
* `RemoveFromInfrastructure`
* `InRecycleBin`

Add error code for ElfMachine fails

---

go.mod
go.sum
test/e2e/config/elf-dev.yaml

CAPI v1.2.6: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.6

Upgrade CAPI to v1.2.6

---

templates/cluster-template.yaml

ELF Host 重启之后 kube-vip:v0.4.2 未能恢复，导致 K8s 集群失败。
升级 kube-vip 到 v0.5.7，持续观察结果。
使用 kube-vip v.0.5.7 进行创建、扩缩容、升级集群等操作，操作皆可正常进行。

Upgrade kube-vip to v0.5.7

---

controllers/elfmachine_controller.go
controllers/tower_cache.go
controllers/tower_cache_test.go
pkg/service/errors.go
pkg/util/tower.go
test/fake/tower.go

当 ELF 集群内存不足，CAPE 会一直重试创建虚拟机。
当 ELF 内存不足的时候，优化创建虚拟机的逻辑。
当检测到 ELF 集群继续资源不足，在 CAPE 设置内存内存不足的标记，这样在该 ELF 集群创建虚拟机的任务就不再继续重试（一直到标记取消）。
设置间隔五分钟，超过了五分钟之后，每隔五分钟允许一次创建虚拟机的尝试。如果尝试成功会取消内存资源不足的标记，这样其他创建虚拟机的任务会继续进行。
内存不足的时候也可能导致虚拟机不能正常开机，这部分也需要处理。
**存在的问题：**
1. 资源不足的标记需要使用锁，带来了性能开销
2. 每次 CAPE 刚启动的时候还是会并发的创建虚拟机
3. 当 ELF 内存资源不足标记取消之后，其他任务会继续并发创建，不能准确预判还有多少资源
创建一个 1 CP + 多 Worker 集群，资源只够创建部分节点，显示其他的 Worker 因为资源不足等待创建。五分钟后有一个 Worker 节点尝试创建。
释放该 ELF 内存资源后，其他 Worker 恢复正常创建。

Optimize the creation of virtual machines when insufficient memory detected for ELF cluster

---

config/manager/manager.yaml
controllers/elfmachine_controller.go
controllers/tower_cache.go
controllers/tower_cache_test.go
controllers/vm_limiter.go
controllers/vm_limiter_test.go
main.go
pkg/config/vm.go

ELF 集群在同时创建大量的虚拟机可能会带来一些性能问题导致创建虚拟机任务失败，或者出现重名虚拟机。
CAPE 支持限制并发创建虚拟机数量，减少对 ELF API产生的压力和性能影响。
并发创建两个 3CP + 20 Workers 集群
第一次测试
```bash
haijian-elf-test38   v1.23.14   Ready      true    3/3             20/20     7m41s   calico   smtx-zbs-csi   10.255.160.2:6443
haijian-elf-test37   v1.23.14   Ready      true    3/3             20/20     9m18s   calico   smtx-zbs-csi   10.255.160.3:6443
```
第二次测试
```bash
haijian-elf-test2    v1.23.14   Ready      true    3/3             20/20     8m13s   calico   smtx-zbs-csi   10.255.160.3:6443
haijian-elf-test1    v1.23.14   Ready      true    3/3             20/20     8m23s   calico   smtx-zbs-csi   10.255.160.2:6443
```

Support the max concurrent number of virtual machine creation

---

controllers/elfmachine_controller.go

取消对 CP 节点虚拟机创建的限流，加速集群的创建过程。
单个ElfCluster中的多个CP节点是逐个按顺序创建的，此PR允许任意ElfCluster中的CP节点VM创建都不受限流约束。
并发创建两个 3CP + 20 Workers 集群
第一次
```bash
haijian-limit-test2   v1.23.14   Ready      true    3/3             20/20     10m     calico   smtx-zbs-csi   10.255.160.2:6443
haijian-limit-test3   v1.23.14   Ready      true    3/3             20/20     11m     calico   smtx-zbs-csi   10.255.160.3:6443
```
第二次
```bash
haijian-limit-test2   v1.23.14   Ready      true    3/3             20/20     10m     calico   smtx-zbs-csi   10.255.160.2:6443
haijian-limit-test3   v1.23.14   Ready      true    3/3             20/20     10m     calico   smtx-zbs-csi   10.255.160.3:6443
```
第三次
```bash
haijian-limit-test2   v1.23.14   Ready      true    3/3             20/20     9m36s   calico   smtx-zbs-csi …
```

Allow the concurrent creation of Control Plane VMs in different ElfClusters

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
pkg/service/vm.go

问题：删除集群，对应的标签 cluster-name 和 vip 未被清理。
解决：之前相关的删除逻辑加入了计数判断，但是目前的计数是不准确的。在删除集群的时候直接删除集群关联的标签即可。
经过多次删除集群测试，上述没有被删除的标签都被删除了。

SKS-1140: Delete the labels of the cluster when the cluster is deleted

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
controllers/vm_limiter.go
controllers/vm_limiter_test.go
pkg/config/config.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go

问题：Reconcile ElfMachine 过期数据，导致创建放置组的 taskRef 被删除了，操作放置组的锁不能被释放，创建集群时间增加。
解决：放置组操作 task 的时间在秒级别，通过轮询等待放置组操作 task 完成（3秒），避免了使用 taskRef，从而解决了上述问题。
- 放置组异步操作改成同步执行
- 取消了放置组操作锁
- reconcileVMTask 确保 task 处理完成再设置 ctx.ElfMachine.SetTask("")
已在 CI 完成 6+ 次 E2E 测试验证。

Wait for create/update placement group tasks to finish synchronously

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/resources/placement_group.go
pkg/util/labels/helpers.go
pkg/util/machine/kcp.go
pkg/util/machine/kcp_test.go
pkg/util/machine/machine.go
test/fake/types.go

问题
-
[\[SKS-1135\] KCP Name 超过 63 字符时，CAPE reconcile ElfMachine 失败 - Jira](http://jira.smartx.com/browse/SKS-1135)
CAPI 允许 KCP 那么超过 63 字符，此时，对应 Machine 上的 `cluster.x-k8s.io/control-plane-name` label 值会变为 哈希值，比如：
``` yaml
cluster.x-k8s.io/control-plane-name: hash_YkvElA_z
```
CAPE 直接通过该 label 获取 KCP name 会发生错误：
```
E0403 13:28:13.354540       1 elfmachine_controller.go:397] cape-controller-manager/elfmachine-controller "msg"="failed to reconcile VM" "error"="KubeadmControlPlane.controlplane.cluster.x-k8s.io \"hash_YkvElA_z\" not found" "elfCluster"="huaqing-sks-test-lllllllllllllllllllllllllllllllll" "elfMachine"="huaqing-sks-test-lllllllllllllllllllllllllllllllll-cpcpcpccbvmh" "namespace"="default"
E0403 13:28:13.355101       1 controller.go:326]  "msg"="Reconciler error" "error"="failed …
```

SKS-1135: Fix the issue that KCP name exceed 63 characters

---

go.mod
go.sum

- Bump github.com/onsi/gomega from 1.27.4 to 1.27.6

Upgrade CAPI to v1.4.1

---

api/v1beta1/elfmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachinetemplates.yaml
pkg/service/vm.go

当前 Tower 和 ELF 不会自动设置虚拟机的 GuestOsType，需要在创建虚拟机的时候指定。
为 ElfMachineSpec 新增 OSType 字段描述 GuestOsType，Tower 目前只支持 LINUX 和 WINDOWS。LINUX 为默认值，这样已有的逻辑不需要修改。
需要注意：目前如果创建的虚拟机是 LINUX 系统，但是填写了 WINDOWS，会被自动改成 LINUX。暂未找到原因，不过不影响 CAPE 当前的需求。

SKS-1264: Add osType for ElfMachineTemplate to set VM operation system type

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/resources/placement_group.go

[[SKS-1273] 改进：删除集群的时候应该确保删除相关放置组 - Jira](http://jira.smartx.com/browse/SKS-1273)
删除放置组是一个异步的 task（正常秒级别完成，参考创建放置组）。为了保证删除放置组的可靠性，改成异步等待放置组任务完成。
1.创建 1CP + 1Worker 集群，观察到创建了两个放置组
2.删除集群后，观察到放置组已经被删除

SKS-1273: Delete all related placement groups when deleting a cluster

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go
test/fake/types.go

MD 被删除的时候关联的放置组需要被删除
删除 ElfMachine 前，判断关联的 MD 是否被删除，如果 MD 被删除，先删除关联的放置组再删除 ElfMachine。
SKS 删除 MD 的时候会先缩容为 0 再删除 MD。判断 MD 被删除的条件为：MD 有 DeletionTimestamp 值，或者  *md.Spec.Replicas == 0
1.创建包含两个工作节点组的集群：workergroup1、workergroup2
2.删除节点组 workergroup2，相关的放置组也被删除

SKS-1353: Delete the placement group when the MachineDeployment is deleted

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
test/helpers/cluster.go

[SKS-581] 优化升级3CP+3Worker集群的时间 - Jira http://jira.smartx.com/browse/SKS-581
问题分析文档： https://docs.google.com/document/d/1EZYfWDe_y-XqBoMyBgHiXMRa7sTwSfZy3-5QtfnDltk/edit#
该PR为修复Pod驱逐成功后，Pod仍然存在，致使Machine缩容过慢的问题。
仿照这个CAPV 在CAPE中在删除Machine之前保证删除K8s Node [🐛 Delete node explicitly upon deletion of vm by aartij17 · Pull Request #1551 · kubernetes-sigs/cluster-api-provider-vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1551)
强制关机VM
node删除完成
之后开始删除VM
CAPI日志
06:04:04.573725 开始删除ELFMachine
06:04:35.451257  k8s节点已经找不到，表明已经被CAPE删除
06:04:35.463335 还在等待ELFMachine删除完成
表明，k8s节点在ELFMachine删除时就已经被CAPE删除
```
I0606 06:04:04.573725       1 machine_controller.go:645] "Drain successful" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" …
```

SKS-581: Best effort to delete k8s node before destrying VM

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/service/util.go
pkg/service/util_test.go
pkg/util/kcp/kcp.go

[[SKS-1459] 应该保证 CP 节点运行在不同的主机](http://jira.smartx.com/browse/SKS-1459)
保证所有的 CP 节点必须在不同的主机，如果可用主机数量不够，需要等待有足够的主机再开机。
特例：允许 CP 节点数和可用主机数一样的情况进行升级，会出现两个 CP 节点在同一个主机的中间状态，此时其中一个CP节点并没有加入放置组。
测试环境为 3 可用主机 ELF 集群
1.创建 5 CP 集群，只有前 3 个 CP 正常创建，第四个虚拟机创建但未开机，需要等待足够主机
"The placement group is full, wait for enough available hosts"
2.创建 3 CP 集群，正常创建
3.升级 3 CP 集群，正常升级，没有发生虚拟机迁移

SKS-1459: Make sure the CP nodes are placed on different hosts

---

templates/cluster-template.yaml

[SKS-581] 优化升级3CP+3Worker集群的时间 - Jira http://jira.smartx.com/browse/SKS-581
升级过程中，kube-vip leader切换过慢，导致CAPI驱逐节点上的pod时，偶现访问CP VIP异常
```
I0614 07:34:33.421791       1 machine_controller.go:340] "Draining node" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="sks-e2e-huangwei-sks-581-kubevip-config-101-lgergk/sks-e2e-test-6d2dnk-k8s-upgrade-controlplane-fns8p" namespace="sks-e2e-huangwei-sks-581-kubevip-config-101-lgergk" name="sks-e2e-test-6d2dnk-k8s-upgrade-controlplane-fns8p" reconcileID=02cfddaf-194b-4f80-b8ab-a3a5ec5287fe KubeadmControlPlane="sks-e2e-huangwei-sks-581-kubevip-config-101-lgergk/sks-e2e-test-6d2dnk-k8s-upgrade-controlplane" Cluster="sks-e2e-huangwei-sks-581-kubevip-config-101-lgergk/sks-e2e-test-6d2dnk-k8s-upgrade" …
```

SKS-581: Updating kube-vip configuration to speed up vip leader switching

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
controllers/vm_limiter.go
controllers/vm_limiter_test.go
pkg/service/errors.go

创建放置组的时候偶尔会遇到同名放置组错误，原因是 ELF 中成功创建了该放置组，但是 Tower 却把自己 DB 中的放置组删除了，CAPE 重试创建，Tower 会认为 ELF 已经存在同名放置组而任务失败。Tower 目前大约一个小时定时同步。
Tower 预计在 Q4 修复该问题，CAPE 遇到该问题先增加重试的间隔时间，避免重复的失败任务。
修复单测偶现的一个问题，异步删除资源，需要轮询确认。
1.在没有出现同名放置组的情况，放置组可以正常创建，且手动删除放置组后，Reconcile 的时候会马上重新创建。
2.制造同名放置组错误，观察到创建放置组的逻辑在 30m 内不被允许，过了 30m 后，放置组被正常创建出来。

TOWER-8664: Delay creation of placement group when duplicate placement group is encountered

---

api/v1beta1/conditions_consts.go
api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachinetemplates.yaml
controllers/elfmachine_controller.go
controllers/elfmachine_controller_placement_group.go
controllers/elfmachine_controller_test.go
pkg/config/config.go
pkg/context/machine_context.go
pkg/service/util.go

SKS-1479、SKS-1465 需要更多的讨论，可以在下一个 PR 处理。
当前 PR 主要在 https://github.com/smartxworks/cluster-api-provider-elf/pull/119 的基础上，从“首先创建关机的虚拟机再检查是否有足够主机” 改成 “创建虚拟机前检查是否有足够主机将此虚拟机加入必须策略放置组”。
放置组相关的代码独立到 elfmachine_controller_placement_group.go 方便管理，原有迁移过来的代码逻辑基本上没有调整，主要是针对在创建虚拟机前检查可用主机做了一些微调。
测试环境为 3 可用主机 ELF 集群
1.创建 5 CP 集群，只有前 3 个 CP 正常创建，第四个虚拟机不能创建，需要等待足够主机
"The placement group is full, wait for enough available hosts"
2.创建 3 CP 集群，正常创建，扩容到 5 CP 失败，阻塞在等待可用主机（同上）。
3.升级 3 CP 集群，正常升级，没有发生虚拟机迁移

SKS-1459: Check for available hosts before creating a virtual machine

---

config/rbac/role.yaml
controllers/elfmachine_controller.go
controllers/elfmachine_controller_placement_group.go
controllers/elfmachine_controller_test.go
pkg/util/annotations/helpers.go
pkg/util/kcp/kcp.go

扩容失败后再缩容会被判断为升级，因为根据 *kcp.Spec.Replicas <= kcp.Status.Replicas 判断 KCP 是否正在进行升级不准确。
可用主机不够的情况下，会和 KCP 先扩容再缩容冲突，判断为升级，而把该 CP 放在最新的 Machine 所属的主机上。
KCP 缩容默认会选择最老的 Machine 删除，导致触发一次虚拟机迁移。
操作判断：https://docs.google.com/document/d/1kmq6C4lXcN8WaJ3qwIuRbdkTcyFUKc7F73cbAq3NZaA/edit#heading=h.o4v48qv6y0i
判断滚动第一个 CP 节点改成：*kcp.Spec.Replicas < kcp.Status.Replicas && kcp.Status.UpdatedReplicas == 1
判断缩容改成：*kcp.Spec.Replicas < kcp.Status.Replicas && kcp.Status.Replicas == kcp.Status.UpdatedReplicas
参考文档：https://docs.google.com/document/d/1kmq6C4lXcN8WaJ3qwIuRbdkTcyFUKc7F73cbAq3NZaA/edit#heading=h.3fqxywg14v4w
ELF 集群：3 主机
1.创建 3 CP 集群，可以正常进行升级，没有把升级判断为先扩容后缩容
2.创建 3 CP 集群，扩容为 5 CP，第四个 CP 因为主机不够，虚拟机没有创建出来。等扩容失败后，进行缩容为 3，观察到第四个 CP 的 Machine 被设置了 DeleteMachineAnnotation，然后 KCP 缩容的时候把该 Machine 删除了，KSC 变成 …

SKS-1465: Add DeleteMachineAnnotation to the failed CP Machine when scaling down KCP after a failed scaling up

---

api/v1beta1/elfmachine_types.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
test/helpers/cluster.go

[SKS-1474] CAPE同步VM网络信息慢 - Jira http://jira.smartx.com/browse/SKS-1474。 导致CAPE创建VM时有些时候需要等待3分钟才能从Tower处获取到IP，明显降低了VM创建速度。
ELF同步已安装vmtools的VM的IP数据时，同步时延不固定，快的话1分钟内。慢的话也有2-3分钟的。
ELF同步慢的原因为每次要同步状态的虚拟机太多了，所以导致执行一轮耗费的时间太长。
当Tower API没有返回网卡IP时，从k8s node获取VM第一块网卡IP。VM单网卡场景中可以加快CAPE同步VM IP的速度，加速VM创建过程。
KSC集群创建成功
```
NAME                     K8SVERSION   SKSVERSION   STATUS   READY   CONTROLPLANES   WORKERS   AGE   CNI      CSI            CONTROLPLANEVIP
hw-sks-test-1.24.13-03   v1.24.13     v1.1.0       Ready    true    3/3             3/3       27m   calico   smtx-elf-csi   10.255.26.33:6443
kc get ksc -n default hw-sks-test-1.24.13-03 -ojson | jq .spec.topology
{
"controlPlane": {
"name": "controlplane",
"nodeConfig": {
"cloneMode": "FastClone",
"cpuCores": 4,
"memoryMB": 8192,
"network": { …
```

SKS-1474: Get VM NIC IP from K8s node to speed up VM reconcile

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/util/tower.go

在创建虚拟机的过程删除了相关的 ElfMachine，偶现虚拟机没有被删除。
原因是把 "placeholder-{UUID}" 格式的 UUID 设置给了 vmRef，但虚拟机创建好之后（同步到了 ELF），Tower 把 "placeholder-{UUID}" 改成了 "{UUID}"，但 vmRef 并没有被更新，导致使用 "placeholder-{UUID}" 格式的 vmRef 查不到虚拟机。
不能使用 "placeholder-{UUID}" 格式的 localID 赋值给 vmRef，而是使用 ID 或者 UUID 格式的 localID。
在 MHC E2E 中暂未发现未删除的虚拟机，需要继续再观察多次。

Fix using localID in non-UUID format as vmRef value

---

controllers/elfmachine_controller_test.go
pkg/util/kcp/kcp.go

SKS 1.0 升级到 1.1，3主机环境，5 CP 集群升级到第四个新 CP，没有足够的可用主机，此时缩容为 3，第四个新 CP 没有被删除，导致缩容流程一直阻塞。
可能遇到的几个场景分析：
第四个 CP 需要等待可用主机，此时缩容为 3，kcp.Spec.Replicas 为 3，kcp.Status.UpdatedReplicas 为 4
MachinesSpecUpToDateCondition 为 false
ResizedCondition 为 false，ScalingDownReason
第四个新 CP 需要等待可用主机，此时缩容为 3，kcp.Spec.Replicas 为 3，kcp.Status.UpdatedReplicas 为 4
MachinesSpecUpToDateCondition 为 false
ResizedCondition 为 false，ScalingDownReason
第五个 CP 需要等待可用主机，此时缩容为 3，kcp.Spec.Replicas 为 3，kcp.Status.UpdatedReplicas 为 5
MachinesSpecUpToDateCondition 为 false
ResizedCondition 为 false，ScalingDownReason
第五个新 CP 需要等待可用主机，此时缩容为 3，kcp.Spec.Replicas 为 3，kcp.Status.UpdatedReplicas 为 5
MachinesSpecUpToDateCondition 为 true
ResizedCondition 为 false，ScalingDownReason
正常滚动更新过程，会出现 ResizedCondition 为 …

SKS-1573: Add DeleteMachineAnnotation to the failed CP Machine when scaling down KCP after a failed rolling update

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go

原有的 reconcileVM 只关注虚拟机是否处于 Running 状态，没有考虑放置组的情况。
日志 "VM state is not reconciled" 日志并不能准确的知道是不满足什么条件导致不能后续的 reconcile。
此外，"VM state is not reconciled" 会重复打印一些没有价值的日志，reconcileVM 本身已经打印了具体的日志。
reconcileVM 增加返回一个 bool，如果为 true 表示 reconcileVM 已经达到了预期。这样就可以由 reconcileVM 自身决定是否达到了预期，而不需要在调用 reconcileVM 之外再做一次判断。同时也减少了日志 "VM state is not reconciled"。
3 主机环境，1 CP + 1 Worker 集群
以下操作均成功：
1. 创建集群
2. 1 CP 扩容到 3 CP，1 Worker 扩容到 3 Worker
3. 删除集群

SKS-1632: Optimize the return value of reconcileVM

---

controllers/elfmachine_controller_placement_group.go
controllers/elfmachine_controller_test.go

[[SKS-1717] 放置组 - 1.0版本的5cp工作负载集群升级后缩容为3cp，放置组中之有一个cp节点 - Jira](http://jira.smartx.com/browse/SKS-1717)
CP 数量大于放置组容量的集群可以进行升级。例如 3可用主机环境，可以升级 5 CP 的集群。预期只能升级前 3个 CP，阻塞在第四个新 CP。
恢复之前删除的代码 `int(*kcp.Spec.Replicas) > usedHostsByPG.Len()`。当放置组已经满了，且 kcp.Spec.Replicas 大于当前放置组已使用的容量的时候，后续的 CP 节点不允许进行滚动更新。
3 主机环境。
1. 5CP 没有使用放置组的集群升级（模拟 1.0 升级到 1.1），前三个新 CP 正常升级，且进入了放置组。第四个新 CP 因可用主机不够阻塞。这个时候手动缩容为 3CP，第四个新 CP 被自动删除。集群完成升级。
2. 3 CP 集群可以正常升级。
3. 3CP 集群扩容到 3CP，第四个 CP 因可用主机不够阻塞。手动缩容到 3CP，第四个 CP 被自动删除，恢复正常。

SKS-1717: Stop rolling out more CP VM when the placement group is full and KCP replicas is greater than host count

---

controllers/vm_limiter.go

Tower 在创建放置组的 task 中增加了检测到放置组已经存在会触发一次放置组数据同步。
正常情况下放置组同步在一分钟内完成，考虑到出现同名放置组的时候 ELF 服务不稳定，暂把重试时间设置为 5m。
需要等待 Tower 发版部署后，CAPE 发版后通过 E2E 验证。

SKS-1691: Decrease the retry interval for creating placement groups to 5 minutes

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
controllers/tower_cache.go
controllers/tower_cache_test.go
pkg/service/errors.go

在 3 主机环境创建 3CP 集群后，其中一个主机故障后，主机所在的 CP 虚拟机关机，CAPE 会尝试启动该虚拟机。因为 CP 使用了必须在不同主机的放置组，所以 ELF 尝试启动该虚拟机失败。
跟之前内存不足一样，通过检测 ELF 返回的错误信息，如果发现是不满足放置组规则，每隔五分钟再运行创建或关机逻辑。
在 3 主机环境创建 3CP 集群，然后使其中一个主机不可用，之后该主机所在的 CP 被关机，CAPE 会使用上述的策略进行尝试开机。
因改动了原来内存不足重试的逻辑，也测试了这部分，这次改动没有影响：

SKS-1707: Optimize the creation/power on of virtual machines when PlacementGroupFilter detected for placement group

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/config/vm.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go

当前 ELF 允许同名虚拟机存在，Tower 不允许通过 API 创建同名虚拟机。但 Tower 目前在同步 VM 到 ELF 超时失败后，会删除本地 DB 的虚拟机记录，但如果这个时候 ELF 成功创建了该虚拟机。如果再通过 Tower API 重试创建该虚拟机，就有可能出现两个同名的虚拟机。但目前 CAPE 只能使用其他一个虚拟机。
Tower 预计未来会解决同名虚拟机的问题。在 Tower 解决该问题之前，CAPE 需要自动检测同名虚拟机，如果发现同名虚拟机，需要自动把不使用的虚拟机删除。
在当前的 ElfMachine reconcile 和删除 ElfMachine 的逻辑，在不影响现有逻辑和功能的前提下加入根据虚拟机名称找到同名虚拟机的代码。
如果考虑性能问题，可以考虑增加检测同名虚拟机的间隔时间（6m 等），例如在 ElfMachine 记录每次同名检测的时间。
可以考虑仅在创建 ElfMachine 一个时间段内（例如一个小时）做重名虚拟机检查，因为同名虚拟机仅发生在创建虚拟机的过程。
同时创建 1CP + 30+ Worker 集群，尝试重现同名虚拟机环境。
暂复现一个同名虚拟机，观察到正常 reconcile 会删除重复的虚拟机。
TODO：需要验证在删除集群的时候删除重复的虚拟机。

SKS-1642: Delete duplicate orphan virtual machines

---

api/v1beta1/elfmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachines.yaml

通过 kubectl get elfmachine 的时候，会显示 ECP 的 fake IP.
通过 JSONPath=".status.addresses[?(@.address!=\"240.255.0.1\")].address 过滤 ECP IP，240.255.0.1 是 ECP 固定使用的 IP。
1. addresses: [] 为空
kubectl get elfmachine  
kubectl get elfmachine haijian-test3-controlplane-b7cwh -o=jsonpath="{.status.addresses[*].address}"
2. addresses: [{address: 240.255.0.1, type: InternalIP}]
kubectl get elfmachine (默认使用修改过的CRD column定义，会将ecp fake IP过滤掉)
kubectl get elfmachine haijian-test3-controlplane-b7cwh -o=jsonpath="{.status.addresses[*].address}"
3. addresses: [{address: 240.255.0.1, type: InternalIP},{address: 10.255.3.60, type: InternalIP}]
kubectl get elfmachine
kubectl get elfmachine haijian-test3-controlplane-b7cwh -o=jsonpath="{.status.addresses[*].address}"

SKS-1701: Filter ECP IP when using `kubectl get elfmachine`

---

pkg/service/vm.go

在aarch64集群无法正常执行克隆操作
克隆vm的firmware设置不正确，它应该跟随template设置
- 移除Firmware hardcode设置，使用为空自动跟随template的设置
arm64和amd64，uefi，bios均正常工作

Follow template's firmware settings when cloning vm from template

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
controllers/vm_limiter.go
controllers/vm_limiter_test.go
pkg/service/errors.go
pkg/service/vm.go

同名虚拟机创建任务过于频繁
遇到同名虚拟机，延迟五分钟创建虚拟机。
TODO：vmConcurrentMap、vmOperationMap、placementGroupOperationMap 的数据存在内存泄露，需要 GC。
每五分钟重试一次，符合预期

SKS-1642: Delay creation of vm when duplicate vm is encountered

---

controllers/elfmachine_controller_placement_group.go
controllers/elfmachine_controller_test.go
controllers/vm_limiter_test.go
pkg/config/config.go

当前创建放置组使用了3秒超时时间，而Tower创建放置组的任务超过3秒还没有结束时，会导致 CAPE 没有捕获到 “同名放置组”的错误，从而在requeue时继续创建放置组。
把等待创建放置组的Task的超时时间设置为10秒(因为大多数创建放置组的请求都是只耗时0秒，还有一些是1到9秒不等)。如果等待超时，就认定创建放置组失败，进入5分钟的创建放置组静默期。如果Tower确实遇到创建放置组任务超时，则Tower会主动从ELF同步此放置组，如果Tower在10秒后创建放置组任务成功，则CAPE也会在随后每10秒的requeue中查找到此放置组。
通过给ELF主机CPU加压，能让Tower创建放置组的任务需要10秒以上才能完成，甚至1分钟后超时失败。从而验证此PR的有效性。
`[smartx@node20-216 20:14:13 ~]$ stress-ng -c 4 -l 60`

SKS-1691: Increase the wait timeout for creating placement group to 10s

---

controllers/elfmachine_controller_placement_group.go
controllers/elfmachine_controller_test.go
pkg/config/config.go
pkg/service/vm.go

更新VM放置组这里的超时当前是 3s。观察 CI 能发现这个时间大多数是 0-3s，也有少数 6-10s。
更新放置组和创建放置组一样，超时时间设置为 10s。
创建和删除放置组正常。

SKS-1691: Increase placement group updating timeout to 10s

---

api/v1beta1/elfmachine_types.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
test/fake/types.go

[SKS-1804] 优化ECP CNI场景下，ELFMachine Network Ready的等待时间 - Jira http://jira.smartx.com/browse/SKS-1804
ECP CNI场景下，VM携带有双网卡，一张网卡为静态IP，一张网卡需要DHCP，当前已有的处理无法覆盖该场景。
1. 删除`getK8sNodeIP`方法里面，判断ControlPlaneInitializedCondition的逻辑。当第一个KCP VM获取IP慢时，ControlPlaneInitialized也会在较长时间后才会变成true(经过调查很可能是CAPI的bug)
2. 优化reconcileNetwork方法处理逻辑变更:
- 存在DHCP网卡时，需要所有的DHCP网卡都获取到IP则认为network ready。
- 不存在DHCP网卡时，则至少保证从Tower API/k8s node获取到一个IP，才认为network ready
```
kc get ksc -n default  hw-sks-test-1.24.17-04 -ojson | jq .spec.network.cni
{
"ecpConfig": {
"fakeIP": "100.64.254.254/32",
"ippools": [
{
"cidr": "10.255.67.0/25",
"gateway": "10.255.0.1",
"name": "test",
"subnet": "10.255.0.0/16"
}
],
"uplinkIP": "240.255.0.1/32"
},
"name": "ecp"
}
kc get ksc -n default  hw-sks-test-1.24.17-04 -ojson | jq …
```

SKS-1804: Improve reconcileNetwork() to speed up fetching VM IP

---

Makefile

Fix build image platform error
```
> CONTROLLER_IMG=registry.smtx.io/demo/cape IMAGE_TAG=dev make release
rm -rf out
/Library/Developer/CommandLineTools/usr/bin/make docker-build-all
/Library/Developer/CommandLineTools/usr/bin/make ARCH=amd64 docker-build
docker pull gcr.io/distroless/static:latest
latest: Pulling from distroless/static
Digest: sha256:e7e79fb2947f38ce0fab6061733f7e1959c12b843079042fe13f56ca7b9d178c
Status: Image is up to date for gcr.io/distroless/static:latest
gcr.io/distroless/static:latest
What's Next?
View a summary of image vulnerabilities and recommendations → docker scout quickview gcr.io/distroless/static:latest
docker build --platform linux/amd64 --build-arg ARCH=amd64 --build-arg ldflags="-X 'github.com/smartxworks/cluster-api-provider-elf/pkg/version.buildVersio …
```

Fix multi-architecture image build error

---

Dockerfile
Makefile

Fix arm image build error

---

api/v1beta1/conditions_consts.go
controllers/tower_cache.go
controllers/tower_cache_test.go

新增以下两个 reasons 用于反馈 ELF 集群内存不足和放置组策略不能满足。
- WaitingForELFClusterWithSufficientMemory
- WaitingForPlacementGroupPolicySatisfied
其他需要反馈但已有的 reasons ：
- ShuttingDownFailedReason
- PoweringOffFailedReason
- PoweringOnFailedReason
- WaitingForAvailableHostRequiredByPlacementGroupReason
- JoiningPlacementGroupFailedReason
- WaitingForAvailableHostWithEnoughGPUsReason
- AttachingGPUFailedReason
- DetachingGPUFailedReason

SKS-1914: Add WaitingForPlacementGroupPolicySatisfied and WaitingForELFClusterWithSufficientMemory reasons

---

pkg/config/vm.go
pkg/service/vm.go

增加 Tower URL 到虚拟机描述，在多 Tower 场景下可以区分虚拟机是由哪个 Tower 创建的。

Add CloudTower Server URL to VM description

---

api/v1beta1/elfmachine_types.go
api/v1beta1/types.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/util/patch/finalizer.go

1. CAPE-IP 等 CAPE 设置了 MachineFinalizer 之后，设置了 MachineStaticIPFinalizer，并开始分配 IP
2. CAPE reconcile 获取到的是设置 MachineStaticIPFinalizer 之前的数据，所以此时 reconcile，Finalizers 只有 MachineFinalizer，保存 ElfMachine 的时候 MachineStaticIPFinalizer 被覆盖了（已在本地复现）
3. 如果此时 ElfMachine 被删除，虚拟机还没有创建，所以 ElfMachine 的 MachineFinalizer 很快就被移除。因此 CAPE-IP 没有来得及释放 IP 资源。
CAPE 先检查 ElfMachine 如果需要静态 IP，并且没有设置 MachineStaticIPFinalizer，则等待 CAPE-IP 先把 MachineStaticIPFinalizer 设置好，再继续 reconcile。
而 CAPE-IP 会检查确保 MachineFinalizer 和 MachineStaticIPFinalizer 都存在的情况下，再分配 IP。这样就不会存在分配了 IP 但是没有设置 MachineStaticIPFinalizer 的情况。
1. 创建使用静态 IP 的 1CP + 3Workers 集群正常，删除也正常。
2. 模拟脏数据没有复现静态 IP 没有被释放。
```go
// 1. 在代码中使用 elfMachine.Finalizers = nil，模拟使用脏数据
ctx.ElfMachine.Finalizers = nil
if !ctrlutil.ContainsFinalizer(ctx.ElfMachine, …
```

SKS-1840: Make sure adding MachineFinalizer won't overwrite MachineStaticIPFinalizer

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_gpu_test.go
pkg/util/labels/helpers.go
pkg/util/labels/helpers_test.go

问题
-
[\[SKS-1978\] 自动伸缩支持 GPU 资源 - Jira](http://jira.smartx.com/browse/SKS-1978)
slack: https://smartx1.slack.com/archives/C037V8QMKQA/p1698722686956959
pod 请求 GPU 触发自动扩容 GPU 节点后，在新节点 GPU 资源 ready 前，被缩容了。
原因是 Node 已经 ready，但 CA 不知道它是带 GPU 的节点。
需要按照 https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#special-note-on-gpu-instances 给 node 打 label，让 CA 知道 node 正在准备 GPU 资源。
修改
-
- 给带 GPU 的 node 打 label `cluster-api/accelerator`，值为第一个 GPU 或 vGPU 的类型
测试
-
创建 GPU 节点，在 Node 创建后，很快打上了 `cluster-api/accelerator` label：
触发 GPU 自动扩容：
新 node 创建后也有 `cluster-api/accelerator` label：
CA 日志显示该 node 的 GPU 资源还不 ready，pending 的 pod 可以被调度到 CA 模拟的正在扩容的节点上，不会触发缩容和额外的扩容：
最终 GPU 资源 ready，pod 成功被调度，自动扩容流程顺利结束，event:
删除 GPU 负载 Pod，自动缩容成功：

SKS-1978: Add 'cluster-api/accelerator' label to GPU node to support autoscaling

---

api/v1beta1/elfmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_elfmachinetemplates.yaml
controllers/elfmachine_controller.go
controllers/elfmachine_controller_gpu.go
controllers/elfmachine_controller_gpu_test.go
controllers/elfmachine_controller_test.go
controllers/tower_cache.go
controllers/tower_cache_test.go
controllers/vm_limiter.go
controllers/vm_limiter_test.go
go.mod
go.sum
pkg/service/collections.go
pkg/service/collections_test.go
pkg/service/errors.go
pkg/service/mock_services/vm_mock.go
pkg/service/types.go
pkg/service/util.go
pkg/service/util_test.go
pkg/service/vm.go
test/e2e/vm_helpers.go
test/fake/tower.go

相关文档 [CAPE 支持 GPU](https://docs.google.com/document/d/1tAinrp-iE6l2WkmRsKis1SaXdTGqKH15KajZ5qcaNSk/edit#heading=h.jv4qcx1lypv)
测试环境
host1: 1 张 Tesla T4，host2：2 张 Tesla T4 + 1 张 Tesla V100，host3：1 张  Tesla T4 + 1 张 V100（4 vGPU）
1. 创 1 V100 的节点组，可以创建出来 4 个 workers，剩余的 2 个 worker 没有足够的 vGPU 没有创建出来，没有出现 GPU 重复挂载和卸载。
```yaml
name: workergroup1
replicas: 6
nodeConfig:
cpuCores: 8
memoryMB: 12288
cloneMode: FastClone
vgpuDevices:
- type: "GRID V100-4C"
count: 1
```
2. 创 2 V100 的节点组，可以创建出来 2 个 workers，剩余的 4 个 worker 没有足够的 vGPU 没有创建出来，没有出现 GPU 重复挂载和卸载。
```yaml
name: workergroup1
replicas: 6
nodeConfig:
cpuCores: 8
memoryMB: 12288
cloneMode: FastClone
vgpuDevices:
- type: "GRID V100-4C"
count: 2
```
3. 创 3 V100 的节点组，可以创建出来 1 个 workers，剩余的 5 个 worker 没有足够的 vGPU 没有创建出来，没有出现 GPU 重复挂载和卸载。
```yaml
name: …
```

Add support for vGPU

---

config/manager/manager.yaml

[[SKS-2097] 集群有一个节点失联时应保证已有Deployment能正常工作 - Jira](http://jira.smartx.com/browse/SKS-2097)

SKS-2097: Ensure CAPE Deployment can work when a node in the cluster is disconnected

---

pkg/service/vm.go

SKS 创建 GPU 直通集群时，虚拟机配置了 GPU，但是实际挂载的是 vGPU。
如图所示，where 实际没有设置值，所以没有生效，导致返回了 GPU + vGPU 设备。gpuDeviceUsage 没有指定，而 GPU 和 vGPU 的 model（Tesla T4） 是一样的，导致 vGPU 设备被判断成 GPU。
1. 集群有三张 Tesla T4 卡，把其中一张卡切成 vGPU。
2. 创建 1CP + 3Worker 集群，每个 Worker 配置一张 Tesla T4 直通。
3. 集群创建完成，观察到其中一个 Worker 挂载了 vGPU
查询 GPU 信息的时候指定正确的 where （gpuDeviceUsage 和主机 ID）查询条件。
1. 集群有三张 Tesla T4 卡，把其中一张卡切成 vGPU。
2. 创建 1CP + 3Worker 集群，每个 Worker 配置一张 Tesla T4 直通。
3. 集群创建有两个 Worker 挂载了 Tesla T4，剩下的一个 Worker haijian-gpu-workergroup1-ltp5m 没有挂载 vGPU，在等待足够可用的 GPU 直通设备。
```bash
No host with the required GPU devices for the virtual machine, so wait for enough available hosts" namespace="default" elfCluster="haijian-gpu" elfMachine="haijian-gpu-workergroup1-ltp5m" machine="haijian-gpu-workergroup1-nwfxx-nd6q5"
```
被切成 vGPU 的 Tesla T4 …

SKS-2160: Fix 'where' condition when getting GPU device allocation details

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
controllers/elfmachine_controller_placement_group.go
controllers/elfmachine_controller_test.go
controllers/tower_cache.go
controllers/tower_cache_test.go
controllers/vm_limiter.go
controllers/vm_limiter_test.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go

在一个SKS创建的所有工作负载集群包含一百几十个节点的环境中，获取Tower放置组API的调用量会很大（包含 CAPE 和其他的方式的）。
CAPE 每个节点关联了一个放置组，放置组是节点组之间共享的。
当前每个节点 Reconcile 的时候都会通过 Tower API 获取放置组的信息（两次），一次是确认放置组是否存在，一次是确认节点对应的虚拟机是否还在放置组。
CAPE 默认 10-15m 就 resync，这个时候所有的节点都会 Reconcile 一次，也就意味着需要从 Tower 获取两次放置组信息，这样会重复从 Tower 获取放置组信息。
多个节点是共享放置组的，所以放置组读多写少，考虑使用缓存，减少对 Tower API 的访问。
如果修改了放置组，需要及时删除放置组缓存。并且在删除放置组的时候也应该马上删除放置组缓存，防止马上创建同名放置组的时候使用到过期的缓存。
[连续八次通过 E2E](https://jenkins.caas.smtx.io/blue/organizations/jenkins/kubesmart/detail/haijian%2Ftest)
需要进一步观察修改前和修改后减少的接口访问量对比。新版代码从 2023-12-05 16:50 开始运行。[监控](https://grafana.tower.smtx.io/explore?panes=%7B%22p9A%22:%7B%22datasource%22:%22Wa0h_GbVk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcloudtower%3D%5C%2210.255.0.4%5C%22,%20pod%3D%5C%22ingress-nginx-controller-tkvs7%5C%22%7D%2 …

SKS-2157: Cache placement group to reduce Tower API requests

---

api/v1beta1/consts.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_placement_group.go
pkg/service/util.go
pkg/service/util_test.go
pkg/service/vm.go
pkg/util/annotations/helpers.go
pkg/util/machine/machine.go
pkg/util/machine/machine_test.go
pkg/util/tower.go
pkg/util/types/uuid.go
pkg/util/types/uuid_test.go

支持指定集群和节点虚拟机的所属用户。
ElfCluster 支持设置 CreatedByAnnotation 注解，在创建虚拟机的时候使用 CreatedByAnnotation 设置 Owner。
CreatedByAnnotation 支持以下两种方式的值：
1. ${Tower username}@${Tower auth_config_id} 例如 caas.smartx@7e98ecbb-779e-43f6-8330-1bc1d29fffc7.
2. ${Tower username} 例如 root
1. 没有设置 CreatedByAnnotation
ksc 和 elfCluster 没有设置 CreatedByAnnotation，观察到创建出来的虚拟机也没有设置 Owner
2. 设置 CreatedByAnnotation，且值为 ${Tower username}@${Tower auth_config_id}  格式
ksc 和 elfCluster 没有设置 CreatedByAnnotation 为 haijian.yang@d8dc20fc-e197-41da-83b6-c903c88663fd，观察到创建出来的虚拟机带上了指定的 Owner
3. 设置 CreatedByAnnotation，且值为 ${Tower username} 格式

SKS-2193: Support setting the owner of ElfCluster and virtual machines 

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
controllers/tower_cache.go
controllers/tower_cache_test.go

https://github.com/smartxworks/cluster-api-provider-elf/pull/162 给虚拟机增加虚拟机后，Tower 会自动给虚拟机添加系统标签导致 CAPE 不能给虚拟机添加预期的标签。
```go
// 已经有了系统标签，导致没有进入 if 执行。
if len(vm.Labels) == 0 {
if ok, err := r.reconcileLabels(ctx, vm); !ok {
return reconcile.Result{}, errors.Wrapf(err, "failed to reconcile labels")
}
}
```
如果虚拟机打上了 managed 标签就认为所有的标签就有了，就可以跳过给虚拟机加标签的逻辑。
考虑每次 Reconcile 都要从 Tower 获取 managed 标签，且 managed 标签除非被人为删除，否则不会变动。为了减少 Tower 接口访问，managed 会缓存 30m。
创建 1CP + 3Workers 集群，在 ElfCluster 指定 haijian.yang@d8dc20fc-e197-41da-83b6-c903c88663fd。
观察到虚拟机指定了 owner
虚拟机也打上了预期的标签

SKS-2194: Fix labeling virtual machines

---

pkg/service/vm.go

在 ELF 嵌套集群（非嵌套暂未复现）环境创建任意的集群后删除集群，一定概率可以复现。
在本地创建多个同名字前缀的放置组，然后连续两次调用 DeleteVMPlacementGroupsByNamePrefix 函数，也出现了重复删除删除放置组的任务。因此可以判断，Tower 没有做幂等处理，导致第二次删除的时候，放置组的 EntityAsyncStatus 还是 nil，因此产生重复的删除任务。
```go
deleteVMPlacementGroupParams := clientvmplacementgroup.NewDeleteVMPlacementGroupParams()
deleteVMPlacementGroupParams.RequestBody = &models.VMPlacementGroupDeletionParams{
Where: &models.VMPlacementGroupWhereInput{
NameStartsWith:       TowerString(namePrefix),
EntityAsyncStatusNot: nil,
},
}
```
综上述，删除集群的时候，连续两次 Reconcile ElfCluster 可能会出现该问题。
Tower 没有做幂等处理，难以避免删除重复的删除任务，只能尽可能降低出现重复删除任务的概率。
恢复最开始的方式，设置超时时间，轮询删除任务，这样可以避免短时间内两次连续的 Reconcile ElfCluster。
```go
withLatestStatusTask, err := svr.WaitTask(ctx, taskID, config.WaitTaskTimeoutForPlacementGroupOperation, config.WaitTaskInterval) …
```

SKS-2227: Fix deleting a PG might create multiple deletion tasks at the same time

---

controllers/elfmachine_controller_gpu.go
controllers/elfmachine_controller_gpu_test.go
pkg/service/collections.go
pkg/service/collections_test.go
pkg/service/util.go
pkg/service/util_test.go

[SKS-2342](http://jira.smartx.com/browse/SKS-2342) GPU/vGPU - 计算挂载虚拟机时没有过滤回收站和关机状态的虚拟机
GPU 在计算挂载虚拟机时过滤回收站和关机状态的虚拟机。
而 vGPU 直接使用 AvailableVgpusNum 即可（回收站和关机状态的虚拟机都不会统计）。
判断 GPUs  是否可用，每个 GPU 要满足以下要求（参考代码 HasGPUsCanNotBeUsedForVM）：
✅GPU 没有挂载任何虚拟机（不包括在回收站和关机状态） 
✅GPU 只挂载了一个虚拟机（不包括在回收站和关机状态），且是当前虚拟机
❌其他情况不可用
判断 vGPUs 是否可用（参考代码 HasGPUsCanNotBeUsedForVM）：
✅所有的 vGPUs 可分配数量满足虚拟机的需求
❌其他情况不可用
1.1 创建一个关机状态的虚拟机，并挂载了 T4。
1.2 创建 1CP + 1Worker（挂载 1T4） 集群，观察到 Worker 仍然可以挂载上述关机状态虚拟机挂载的 T4
2.1 创建一个关机状态的虚拟机，并挂载了 T4，然后放入回收站。
2.2 创建 1CP + 1Worker（挂载 1T4） 集群，观察到 Worker 仍然可以挂载上述在回收站虚拟机挂载的 T4
1.1 创建一个关机状态的虚拟机，并挂载了一个 GRID T4-4C。
1.2 创建 1CP + 1Worker（挂载一个 GRID T4-4C） 集群，观察到 Worker 仍然可以挂载上述关机状态虚拟机挂载的 GRID T4-4C
2.1 创建一个关机状态的虚拟机，挂载了一个 GRID T4-4C，并放入回收站。
2.2 创建 1CP + 1Worker（挂载一个 GRID T4-4C） 集群，观察到 Worker …

SKS-2342: Exclude the VMs in shutdown state or in the recycle bin when calculating the number of GPU mounts

---

controllers/elfcluster_controller.go
controllers/elfcluster_controller_test.go
controllers/vm_limiter.go
pkg/service/mock_services/vm_mock.go
pkg/service/vm.go

当前 Tower 每个标签都有一个虚拟机引用计数，这个计数是异步同步近实时更新的。
例如删除一个标签关联的虚拟机之后，标签的计数更新时间可能在 1 秒内，也可能几秒之后。
当前 CAPE 删除 ClusterNameLabel 和 NamespaceLabel 的时候会判断标签的虚拟机引用计数是否大于等于 0，
只有引用计数大于等于 0 的时候才会删除该标签。
因此，CAPE 在删除 ClusterNameLabel 和 NamespaceLabel 的时候会存在遗删的可能。
定期清理（每天一次）没有被使用的 Tower 标签。
为了避免误删在使用的标签，清理标签的时候增加只能清理一天前创建的限制。
程序运行之前，Tower 有很多一天前创建的标签
程序运行之后，新建一个集群，观察到只剩下当前集群使用的标签

SKS-2344: Clean unused CloudTower labels created by CAPE every 24h

---

controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
pkg/config/config.go
pkg/util/machine/machine.go

[SKS-2387](http://jira.smartx.com/browse/SKS-2387) 在虚拟机操作系统中执行 shutdown 命令关机后 CAPE 没有及时开机，需要等默认的 10m 分钟 resync。
Tower -> ELF -> VM
当前 Tower 不支持 Watch 虚拟机的状态，所以我们不能实时感知虚拟机被关机了。
Tower 每隔 20s 从 ELF  定时同步虚拟机，一般情况下 30s 左右完成。
CAPI Machine 控制器会实时感知节点的变化。观察到如果虚拟机关机了，那么 Machine 会设置 NodeHealthy 为 Unknown（[相关代码](https://github.com/kubernetes-sigs/cluster-api/blob/caa378c55af88599903f3c0e48799fd697e36049/internal/controllers/machine/machine_controller_noderef.go#L152)）
```yaml
lastTransitionTime: "2024-01-19T08:47:56Z"
message: 'Node condition MemoryPressure is Unknown. Node condition DiskPressure
is Unknown. Node condition PIDPressure is Unknown. Node condition Ready is Unknown. '
reason: NodeConditionsFailed
status: Unknown
type: NodeHealthy
```
因此可以 CAPE  可以通过检测 Machine 是否设置了 NodeHealthy 为 …

SKS-2387: Requeue ElfMachine when NodeHealthy condition is unknown to ensure the VM can be powered on ASAP

---

api/v1beta1/conditions_consts.go
controllers/elfmachine_controller.go
controllers/elfmachine_controller_test.go
controllers/tower_cache.go
controllers/tower_cache_test.go
pkg/service/errors.go

集群存储不足时，创建节点 VM 任务不断重试，创建出多个重复的同名 volume。
* 创建虚拟机的时候如果检测到存储不足，延迟五分钟允许重试。参考之前内存不足的处理：https://github.com/smartxworks/cluster-api-provider-elf/pull/79
* reconcileVMFailedTask 拆成两个 Switch 处理，第一个 Switch 根据任务类型处理，第二个 Switch 根据错误的类型处理（不同类型测任务可能产生同样的错误）。
SMTX OS 6.0 未复现多个重复的同名 volume，因此不需处理。
1. 把集群的存储资源机会消耗完
2. 创建任意数量节点的集群，观察到存储不足导致节点无法创建，并每隔五分钟后允许重试

SKS-1390: Optimize the creation of virtual machines when insufficient storage detected for ELF cluster

---

PROJECT
config/webhook/manifests.yaml
go.mod
main.go
test/helpers/envtest.go
webhooks/elfmachine_webhook_mutation_test.go
webhooks/elfmachinetemplate_webhook_mutation.go
webhooks/elfmachinetemplate_webhook_mutation_test.go

简化 IPPool 的配置，默认情况下只需要配置 IPPool name 即可，可以不填写 apiGroup 和 kind。
CAPE 当前使用 ipam.metal3.io IPPool 作为默认的 IP Pool，在 ElfMachineTemplate webhook 默认设置即可，这样创建出来的 ElfMachine 会自动使用默认的 IPPool 配置。
1.ElfMachineTemplate 未设置 `apiGroup` 和 `kind` 的 IPPool
```yaml
network:
devices:
- addressesFromPools:
- name: ip-pool-node
```
2. 观察到 addressesFromPools 被设置了 `ipam.metal3.io` 和 `IPPool`
```yaml
network:
devices:
- addressesFromPools:
- apiGroup: ipam.metal3.io
kind: IPPool
name: ip-pool-node
```
3. 创建出来的 ElfMachine 的 addressesFromPools 设置了`ipam.metal3.io` 和 `IPPool`

SKS-1825: Set the default APIGroup and Kind for IPPool CR used in ElfMachineTemplate

---

templates/cluster-template.yaml

- https://github.com/kube-vip/kube-vip/issues/684 解决方法：[CAPV ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/templates/cluster-template.yaml#L184)。已经按照 Issue 描述的方法处理。
- https://github.com/kube-vip/kube-vip/issues/692 Kubernetes v1.29 不支持 v0.7.1 使用的 hostAliases。经过验证，这个不影响 CAPE 的使用。
[v0.7.1](https://github.com/kube-vip/kube-vip/releases/tag/v0.7.1)
- Added common endpoint provider interface and fixed route deletion iss… by @p-strusiewiczsurmacki-mobica in https://github.com/kube-vip/kube-vip/pull/761
- Bump golang from 1.21.6-alpine3.18 to 1.22.0-alpine3.18 by https://github.com/dependabot in https://github.com/kube-vip/kube-vip/pull/760
-Fix IPVS service error: netlink receive invalid argument by @lou-lan in https://github.com/kube-vip/kube-vip/pull/765
- Added …

SKS-2437: Bump kube-vip to v0.7.1

---

pkg/manager/manager.go
pkg/vendor/vendor.go

1. 没有配置 HOST_CONFIG_AGENT_API_GROUP
agentv1.GroupVersion: kubesmart.smtx.io
agentv1.SchemeBuilder.GroupVersion: kubesmart.smtx.io/v1alpha1
2. HOST_CONFIG_AGENT_API_GROUP=kubesmart.arcfra.io
agentv1.GroupVersion: kubesmart.arcfra.io
agentv1.SchemeBuilder.GroupVersion: kubesmart.arcfra.io/v1alpha1

SKS-3010: Support custom host agent group

---

config/manager/manager.yaml
config/rbac/kustomization.yaml
config/rbac/leader_election_role_binding.yaml
config/rbac/role.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml
controllers/elfmachine_controller.go

ticket
-
[\[SKS-3173\] \[CAPE\] cape-controller 和 cape-ip-controller 混用了 RBAC 权限 - Jira](http://jira.smartx.com/browse/SKS-3173)
cape-controller 和 cape-ip-controller 都是用 default sa，导致它们的 RBAC 混用了。
changed
-
- 使用 cape-controller-manager ServiceAccount 
- 添加 elfmachinetemplate 权限
test
-
生成的 manifests:
在未添加 elfmachinetemplate 时修改 elfmachine，webhook 会报错无权限：
添加 elfmachinetemplate 后再修改，正确报错：

SKS-3173: Use cape-controller-manager ServiceAccount & fix elfMachineTemplate permissions

---

config/webhook/manifests.yaml
webhooks/elfmachine_webhook_mutation.go
webhooks/elfmachine_webhook_mutation_test.go
webhooks/elfmachine_webhook_validation.go

问题
-
[\[SKS-3181\] \[CAPE\] elfMachine 的 mutation webhook 没有处理 UPDATE - Jira](http://jira.smartx.com/browse/SKS-3181)
elfMachine 的 mutation webhook 没有拦截 UPDATE 事件。
在部分场景下（升级 SKS），elfMachine 需要在 UPDATE 中设置默认值。
修改
-
- 给 elfMachine 的 mutation webhook 增加 UPDATE verbs
- 完善 elfMachine 的 webhook
测试
-
环境中的 webhook 正确更新:

SKS-3181: Should hook elfMachine UPDATE verbs in mutation webhook

---

api/v1beta1/conditions_consts.go
controllers/elfmachine_controller_gpu.go
controllers/elfmachine_controller_gpu_test.go

没有足够内存的主机设置的 WaitingForAvailableHostWithEnoughGPUsReason 表达的信息不够清晰
当没有足够内存的时候的时候设置 WaitingForAvailableHostWithSufficientMemoryReason
1. GPU 足够但主机内存不足

SKS-2999: Set WaitingForAvailableHostWithSufficientMemoryReason when no sufficient memory hosts

---

api/v1beta1/conditions_consts.go
controllers/elfmachine_controller_gpu.go
controllers/elfmachine_controller_gpu_test.go

https://github.com/smartxworks/cluster-api-provider-elf/pull/189

SKS-3242: Replace WaitingForAvailableHostWithSufficientMemory with WaitingForELFClusterWithSufficientMemory

---

pkg/hostagent/tasks/expand_root_partition.yaml

ticket
-
[\[SKS-3327\] 原地更新 - ARM的集群，磁盘扩容，原地更新失败 - Jira](http://jira.smartx.com/browse/SKS-3327)
根因： openEuler 的根目录分区是 vda3，playbook 中写死了 vda2 导致失败：
changes
-
- 优化 expand_root_partition.yaml
- 从 ansible facts 中提取根目录的挂载设备和分区
- 调整 shell 语法，兼容 sh 
test
-
- rocky 集群磁盘热扩容成功
- openEuler 磁盘热扩容成功
- 手动在 Kylin 系统中测试 playbook 扩容成功
- 手动在 ubuntu 系统中测试 playbook 扩容成功

improve expand_root_partition.yaml

---

templates/cluster-template.yaml

ticket
-
[\[SKS-3327\] 原地更新 - ARM的集群，磁盘扩容，原地更新失败 - Jira](http://jira.smartx.com/browse/SKS-3327)
https://github.com/smartxworks/cluster-api-provider-elf/pull/191 只修改了 playbook，在创建节点时指定大于模板大小的磁盘还需执行 preKubeadmCommands 中的命令。
changes
-
- 优化 templates/cluster-template.yaml 中 preKubeadmCommands 提示的扩容分区命令，适配更多不同的操作系统
test
-
- 手动测试命令：
- 创建磁盘大于模板的节点成功：

SKS-3327: Improve root partition expanding commands in preKubeadmCommands

---

pkg/manager/manager.go
pkg/product/product.go

CAPE-IP 安装 CAPE 会报错：go: finding module for package [github.com/smartxworks/cluster-api-provider-elf/pkg/vendor](http://github.com/smartxworks/cluster-api-provider-elf/pkg/vendor)
go: [github.com/smartxworks/cluster-api-provider-elf-static-ip](http://github.com/smartxworks/cluster-api-provider-elf-static-ip) imports
        [github.com/smartxworks/cluster-api-provider-elf/pkg/manager](http://github.com/smartxworks/cluster-api-provider-elf/pkg/manager) imports
        [github.com/smartxworks/cluster-api-provider-elf/pkg/vendor](http://github.com/smartxworks/cluster-api-provider-elf/pkg/vendor): module [github.com/smartxworks/cluster-api-provider-elf@latest](http://github.com/smartxworks/cluster-api-provider-elf@latest) found (v1.5.2), but does not contain …

SKS-3570: Rename vendor to product

---

Dockerfile

GitHub workflow 中打包镜像，经常报错：
#14 [builder 5/7] RUN go mod download
#14 182.1 go: github.com/onsi/ginkgo/v2@v2.23.0: read "https://goproxy.cn/github.com/onsi/ginkgo/v2/@v/v2.23.0.zip": stream error: stream ID 1381; INTERNAL_ERROR; received from peer
#14 182.1 go: k8s.io/apiextensions-apiserver@v0.30.3: read "https://goproxy.cn/k8s.io/apiextensions-apiserver/@v/v0.30.3.zip": stream error: stream ID 1405; INTERNAL_ERROR; received from peer
#14 182.1 go: k8s.io/apimachinery@v0.30.3: read "https://goproxy.cn/k8s.io/apimachinery/@v/v0.30.3.zip": stream error: stream ID 1407; INTERNAL_ERROR; received from peer

Update goproxy.cn to proxy.golang.org
